---
- name: Copy apt sources
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    mode: '0644'
    owner: root
    group: root
  notify: Update apt cache

- name: Fix broken
  ansible.builtin.apt:
    state: fixed

- name: Upgrade kernel version
  ansible.builtin.apt:
    name: "{{ prepare_kernel_packages }}"
    update_cache: true
    state: present
  when: prepare_kernel_allow_upgrade | bool
  notify:
    - Update grub
    - Reboot system

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Hold kernel packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ prepare_hold_packages.list }}"
  when:
    - prepare_hold_packages.enable | bool
    # - inventory_hostname in groups.ajorvpn

- name: Upgrade system
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  notify: Reboot system
  when: prepare_allow_upgrade

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install packages
  ansible.builtin.apt:
    name: "{{ prepare_install_packages }}"
    state: present
    update_cache: true

- name: Install debian packages
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop: "{{ prepare_install_packages_deb }}"
  when: prepare_install_packages_deb | length > 0

- name: Enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    # - docker
    - ssh

- name: Enable fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true
  when: prepare_fail2ban_allow_install | bool

- name: Disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - ufw

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
