---
- name: Prepare Servers
  hosts: all
  gather_facts: true
  become: true
  roles:
    - prepare
  tags:
    - prepare

- name: Setup exporters
  gather_facts: true
  hosts: all
  become: true
  roles:
    - exporters
  tags:
    - exporters
