---
# tasks file for roles/exporters
- name: Install python3-pip apt module
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present
    update_cache: true

- name: Install docker pip module
  ansible.builtin.pip:
    name:
      - docker
      - requests==2.32.1
    executable: pip3

- name: Run node-exporter
  ansible.builtin.import_tasks: node-exporter.yml
  tags:
    - node-exporter

- name: Run ping exporter
  ansible.builtin.import_tasks: ping-exporter.yml
  tags:
    - ping-exporter

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
