---
ansible_user: ubuntu
gloabl_kwc_kubeconfig: "/home/{{ ansible_user }}/.kube/config"

arvancloud_cdn_ips:
  - 185.143.232.0/22
  - 92.114.16.80/28
  - 188.229.116.16/29
  - 94.182.182.28/30
  - 185.228.238.0/28
  - 94.182.153.24/29
  - 94.101.182.0/27
  - 2.144.3.128/28
  - 89.45.48.64/28
  - 37.32.16.0/27
  - 37.32.17.0/27
  - 37.32.18.0/27
  - 37.32.19.0/27
  - 185.215.232.0/22
  - 109.230.200.48/29

prepare_change_dns: true
prepare_hold_packages:
  enable: true
  list:
    - linux-image-generic
    - linux-headers-generic
    - linux-image-virtual

prepare_ssh_keys:
  - name: Mahdi Noorbala
    key: YOUR_PUBLIC_SSH_KEY_HERE # noqa yaml[line-length]
