---
# defaults file for roles/exporters
exporters_run:
  node_exporter:
    enable: false
    port: 43212
    image: dockerhub.mirror.dus.de.hajmehdi.nl/prom/node-exporter:v1.6.1
  ping_exporter:
    enable: false
    port: 9427
    image: dockerhub.mirror.dus.de.hajmehdi.nl/czerwonk/ping_exporter:v1.1.3
    config_path: /opt/ping-exporter/config.yml
    configs: "{{ ping_exporter_configs }}"

ping_exporter_configs:
  targets:
    - 1.1.1.1
  settings:
    interval: 2s
    timeout: 3s
    history_size: 42
    size: 120
    dns_addr: 1.1.1.1
    dns_refresh_time: 2m15s
  options:
    - "disableIPv6: false"
